version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    environment:
      - SERVER_PORT=8080
      - DB_PATH=/app/data/payment.db
      - JWT_SECRET=payment_secret_key
      - BLOCKCHAIN_RPC=https://bsc-dataseed1.binance.org/
      - RECEIVER_ADDRESS=0xe27577B0e3920cE35f100f66430de0108cb78a04
      - PAYMENT_TIMEOUT=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  payment-data: